baseURL = "https://jasonmiller.nl/"

languageCode = "en-us"
languageLang = "en"

author = "Jason Miller"
title = "Jason Miller"

disableKinds = ["RSS", "sitemap", "taxonomy", "taxonomyTerm"]

ignoreFiles = [
  "README",
  "node_modules",
  "package.json",
  "package-lock.json",
]

[params]
  email = "contact@jasonmiller.nl"
  dribbble = "https://dribbble.com/imjasonmiller"
  twitter = "https://twitter.com/imjasonmiller"
  github = "https://github.com/imjasonmiller"

[[menu.main]]
  identifier = "work"
  name = "Work"
  url = "/"
  weight = "2"

[[menu.main]]
  parent = "work"
  name = "Work"
  url = "/work/"
  weight = "1"

[[menu.main]]
  identifier = "journal"
  name = "Journal"
  url = "/journal/"
  weight = "0"
