# baseURL: "https://jasonmiller.nl"
baseURL: "https://jasonmiller.nl"
title: "Jason Miller"
metaDataFormat: "yaml"
googleAnalytics: "UA-48049322-3"
disableKinds: ["taxonomy", "RSS"]
permalinks:
   post: /:section/:slug
pygmentsCodeFences: true
pygmentsUseClasses: true
ignoreFiles:
  - README
  - node_modules
  - package.json
  - package-lock.json  