baseURL = "https://jasonmiller.nl/"

languageCode = "en-us"
languageLang = "en"

author = "Jason Miller"
title = "Jason Miller"

disableKinds = [ "taxonomy", "taxonomyTerm"]

enableRobotsTXT = true

[markup]
    [markup.tableOfContents]
        startLevel = 3
        endLevel = 3
        ordered = true
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = false
        tabWidth = 4

ignoreFiles = [
  "README",
  "node_modules",
  "package.json",
  "package-lock.json",
]

[params]
  email = "contact@jasonmiller.nl"
  dribbble = "https://dribbble.com/imjasonmiller"
  twitter = "https://twitter.com/imjasonmiller"
  github = "https://github.com/imjasonmiller"

[[menu.main]]
  identifier = "work"
  name = "Work"
  url = "/"
  weight = "2"

[[menu.main]]
  parent = "work"
  name = "Work"
  url = "/work/"
  weight = "1"

[[menu.main]]
  identifier = "journal"
  name = "Journal"
  url = "/journal/"
  weight = "0"
