version: 2
jobs:
  build:
    docker:
    - image: cibuilds/hugo:0.31.1
    - image: circleci/node:8.7.0

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "Hugo"
          command: HUGO_ENV=production hugo -v -s ~/repo/
      - add_ssh_keys
      - deploy:
          name: "Deployment"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x ./circleci/deploy.sh
              .circleci/deploy.sh
            fi
