version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install hugo
          command: wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_extended_0.49_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - add_ssh_keys
      - deploy:
          name: "Deployment"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x ./.circleci/deploy.sh
              ./.circleci/deploy.sh
            fi
