name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Use Node 15.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0

      - name: Install npm dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Webpack
        run: npm run webpack-prod

      # This uses a forked version of Zola that includes support for the `webp` and `avif` image formats.
      - name: Zola
        uses: docker://imjasonmiller/zola:latest
        with:
          args: build

      # Build the service worker cache
      - name: Build Service Worker cache
        run: npm run sw-cache
         
      - name: Deploy to Netlify
        run: |
          zip -r website.zip public
          curl -H "Content-Type: application/zip" \
            -H "Authorization: Bearer ${{ secrets.NETLIFY_TOKEN }}" \
            --data-binary "@website.zip" \
            https://api.netlify.com/api/v1/sites/jasonmiller.netlify.com/deploys
